### ISSUE TITLE
Give a count to bold/italic/strike mappings

### ISSUE THREAD

**Issue by victorkristof** [SidOfc/mkdx#103]
I really like how wrapping works, it makes it so easy to add markup to text. Most of the time I want to mark in bold or italic a single word only, so using <kbd>\<prefix>b</kbd> is really convenient. But when I want to do it for several words, I need to visually select them first.
 
Would it make sense to add a count to these actions, such that <kbd>[count]\<prefix>b</kbd> would mark the word under cursor and the `[count]` following words in bold?

**Example**

Cursor location indicated by `^`.
```
This is a sentence with bold text.
                        ^
```
I press <kbd>2\<prefix>b</kbd> to obtain
```
This is a sentence with **bold text**.
                          ^
```

**Comment by SidOfc** [comment]
Hi again @victorkristof, you are on :fire: my man, I like it! :+1: 

I think this should also not be too hard to implement and would make sense indeed, thank you for yet another good suggestion <3

**Comment by victorkristof** [comment]
Glad to hear!

By the way, currently <kbd>\<prefix>b</kbd> is applied on a Vim `word`. I think it would make more sense to apply it to a `WORD`.

In fact:
```
This is snake-case.
        ^
```
becomes
```
This is **snake**-case.
        ^
```
when I press <kbd>\<prefix>b</kbd>. But I was expecting
```
This is **snake-case**.
        ^
```

**Comment by SidOfc** [comment]
It depends on how `WORD` is defined for markdown, since if it contains `.` characters it would cause bolding text to include punctuation within bold style, will check it out!

**Comment by SidOfc** [comment]
@victorkristof yoho!

Been working on this a little bit, I think #104 supports all the behavior in this PR and a bit more and actually also fixes some small deficiencies I noticed while testing.

You can pull master to check it out, let me know if anything doesn't work properly for you, otherwise I think this one can be closed :)

**Comment by victorkristof** [comment]
See [my comment](https://github.com/SidOfc/mkdx/issues/101#issuecomment-629693480) in #101 :)

**Comment by SidOfc** [comment]
@victorkristof if you update again it should be fixed, re-merged all features I removed before

**Comment by victorkristof** [comment]
Awesome! The count works perfectly and will be super useful. Thank you!

**Comment by SidOfc** [comment]
Aight, with that I'll close this one, let me know if you see any more issues, feel free to reopen if you do!

Cheers for the suggestion, I may end up using this one myself now as well :)
