### ISSUE TITLE
Syntax file in unexpected location

### ISSUE THREAD

**Issue by pwntester** [SidOfc/mkdx#127]
Hi,

I have a custom syntax that embeds markdown blocks, so my syntax file looks something like:

```
syntax include @markdown syntax/markdown.vim
...
syntax region comment matchgroup=CommentDelimiters start=/^---$/ keepend end=/^---$/  contains=@markdown
```

However, these blocks are highlighted using the built-in markdown syntax rather than MKDX one, since MKDX has its syntax defined in `syntax/markdown/mkdx.vim`. Moving this file to `syntax/markdown.vim` fixes my problem.

Is there any reason why the syntax file is defined in `syntax/markdown/mkdx.vim` rather than `syntax/markdown.vim`. If not, can we move this file?

Thanks,
A

**Comment by SidOfc** [comment]
I'm not sure if this would cause any issues either actually, I'm not sure what my exact reasoning was when I first introduced the syntax file, perhaps just convention.

I'll check this out soon (also another issue that needs some attention so already had plans), If both vim and neovim function normally after the rename it shouldn't be a problem.

Cheers for the feedback :+1:

**Comment by pwntester** [comment]
Thanks for considering it. Just to make it more clear, I could change the path of the include on my plugin, but I expect it to work with any markdown plugins. For example [plasticboy one](https://github.com/plasticboy/vim-markdown/blob/master/syntax/markdown.vim) places the syntax file in the expected location.

Thanks!

**Comment by SidOfc** [comment]
@pwntester you can test it out by updating mkdx, I checked vim and neovim and everything seemed fine. The syntax file should now be in the proper location.

Let me know if it works!

**Comment by pwntester** [comment]
worked thanks!

**Comment by pwntester** [comment]
Oops, seems there is one more change needed in `autoload/mkdx.vim` line 266:

```
let s:util.syn_loadpath  = join([s:util.mkdx_loadpath, 'after/syntax/markdown/mkdx.vim'], '/')
```

**Comment by SidOfc** [comment]
Good catch! Fixed it and checked for other occurrences of `syntax/mkdx`, there are no other cases.
