### ISSUE TITLE
Improve criticmarkup highlighting

### ISSUE THREAD

**Issue by SidOfc** [SidOfc/mkdx#128]
So, something strange happened. 

No change to my vimrc, I just did an update to the last version (you pushed some changes last night and today) and now the conceal is working again. Even the criticmarkup stuff. 

I still have a suggestion: in substitution highlight can you eliminate the opening and closing tags? `{~~` and `~~}` and leavinge only something like `soh~>so`. 

You can see in the picture below how it looks now. 

![criticmarkup](https://user-images.githubusercontent.com/39216570/93586138-64846e80-f997-11ea-9b89-76eb8b50ff89.png)

_Originally posted by @samarulmeu in https://github.com/SidOfc/mkdx/issues/126#issuecomment-694782491_

**Comment by SidOfc** [comment]
@samarulmeu alright this one is done, turns out I forgot to rename some CriticMarkup syntax groups in specific places which prevented them from being concealed. I changed this from a feature request to a bug report as this was in fact a bug in the code, cheers!

Closing this now, feel free to let me know if anything is wrong with it :+1:

**Comment by samarulmeu** [comment]
Nice work. It looks great!

**Comment by samarulmeu** [comment]
Hello!

I do not start a new issue and hope you will get this message.

I started again using CriticMarkup and I find that the highlight option is not rendered nice. Will it be possible to have it only yellow background (no italic and bold, as to not mess with text formatting).

Thank you!

**Comment by SidOfc** [comment]
Hello @samarulmeu, long time since I heard from you :)

CriticMarkup, like any other highlighting added by mkdx, has its own highlighting groups. It is dependent on your theme how these will turn out but you can always manually override them by restyling them in your vimrc. See `:h mkdx-highlight-critic-add` for example, there you can find a list of all CriticMarkup highlight groups and what they are linked to.

See `:h highlight` for more info on how to create/overwrite custom highlights.

**Comment by samarulmeu** [comment]
Hello @SidOfc! 

Thanks for the explanation. I managed to change the colors and font attributes. 

I was silent because the plugin is just working great. Nothing to complain ;). But I am following all the issues and improvements. 

Again, great work!

**Comment by SidOfc** [comment]
Cheers @samarulmeu, and yeah no worries of course, happy to see recurring names :)

Awesome that you found a solution too, in most cases you can probably find hints in the help file or even the README, both are quite expansive :)
