### ISSUE TITLE
breaked into multiple lines after concealing title

### ISSUE THREAD

**Issue by Delayless** [SidOfc/mkdx#129]
![image](https://user-images.githubusercontent.com/42591058/93724626-5e7ecf80-fbdb-11ea-81f8-7f2e9a408433.png)
Maybe it could be optimized about displaying after concealing link.
Thank you!

**Comment by SidOfc** [comment]
Hi @Delayless, this unfortunately is not something I can fix. It seems to be a combination of `set wrap` and `set conceallevel=2`, these are Vim builtins I do not control. Perhaps an idea would be to open an issue on Vim / Neovim for this?

I'll be closing this issue as well, cheers for the feedback!
