### ISSUE TITLE
Fold for header

### ISSUE THREAD

**Issue by ekickx** [SidOfc/mkdx#136]
Currently fold work for toc and fenced code block. Will you consider adding feature to fold header like what vim markdown [does](https://github.com/plasticboy/vim-markdown#folding)?

**Comment by SidOfc** [comment]
Hi @ekickx!

Cheers for the feature request, I've actually dabbled with it in the past but it became quite complex and didn't always work properly so I gave up on it at the time as I'm not a big fan of folds myself (though I can see why others find them useful).

I might take another look to see if it can be done, however I can't say for sure that it will be added or when at the moment. In the meantime I'll keep this issue open as a feature request.

**Comment by ekickx** [comment]
Oh cool. Thanks for the response.

**Comment by SidOfc** [comment]
No problem, I'll keep you posted in this issue as well :+1:

**Comment by matthewmoto** [comment]
I actually had the same request getting set up with this plugin yesterday (which I love, btw).  

Turns out the newer versions of vim support this out of the box if you toss this in your .vimrc/init.vim
```
let g:markdown_folding = 1
```

I'm using it with NeoVim 0.4.3 and mkdx without issue.

**Comment by SidOfc** [comment]
Since this issue has been inactive for quite a while I'm going to close it, thanks for the suggestion @matthewmoto!
