### ISSUE TITLE
Issue with highlighting list items

### ISSUE THREAD

**Issue by douglance** [SidOfc/mkdx#137]
I am using `mkdx` with the `joshdick/onedark.vim` theme. And it is showing this strange highlighting behavior:
<img width="464" alt="Screen Shot 2021-01-19 at 7 11 37 PM" src="https://user-images.githubusercontent.com/4741454/105109240-2c4a8500-5a8a-11eb-994d-ba91080e7c14.png">

If I disable `mkdx`, it goes away. It affects all list modes.

**OS type**:

- [X] Unix (macOS)

**Vim**:

- [x] vim v8.2

**Expected**:

Highlighting should only affect list markers.

**Actual**:

Background color is changed to grey.

**Settings**:

```sh
let g:mkdx#settings     = { 'highlight': { 'enable': 1 },
                        \ 'enter': { 'shift': 1, 'malformed': 1 },
                        \ 'links': { 'external': { 'enable': 1 } },
                        \ 'toc': { 'text': 'Table of Contents', 'update_on_write': 1 },
                        \ 'fold': { 'enable': 1 },
                        \ 'map': { 'prefix': '<leader>' },
                        \ 'auto_update': { 'enable': 1 },
                        \ 'checkbox': { 'update_tree': 2 }}
let g:polyglot_disabled = ['markdown'] 
```

**Comment by SidOfc** [comment]
Hi @douglance!

Cheers for reporting the issue, I'll have a look!

**Comment by SidOfc** [comment]
Hmmn I can't seem to reproduce this using only mkdx and joshdick/onedark, I used the following minimal vimrc (using vim-plug but should be roughly the same for most vim plugin managers):

```viml
syntax on

call plug#begin('~/.vim/plugged')
Plug '~/Dev/sidofc/viml/mkdx'
Plug 'joshdick/onedark.vim'
call plug#end()

colorscheme onedark
```
This is the result I got:
![image](https://user-images.githubusercontent.com/3225058/105224889-14dccc00-5b5e-11eb-92aa-6d87e4856a31.png)

Could you try this vimrc and see if you still get the weird highlighting? You can run vim with a different vimrc using:

```
vim -Nu test-vimrc.vim example-markdown-file.md
```

Of course you'll also need to modify the plugin part to your plugin manager if you don't use vim-plug :)

**Comment by SidOfc** [comment]
Hmmn I actually failed to add the example mkdx settings you used in that initial screenshot, I added them which resulted in this:

![image](https://user-images.githubusercontent.com/3225058/105225280-a4827a80-5b5e-11eb-8136-f914c9070493.png)

Are there any other customizations with regard to the terminal background in your vimrc / other shell config files by any chance?

**Comment by douglance** [comment]
I isolated the culprit:   

`let g:onedark_terminal_italics = 1`

No idea why. Perhaps something to do with italics styling? I am not sure. But I will leave that off for now.

Sorry for blaming your wonderful plugin. The behavior changed when `mkdx` was disabled so I made a bad assumption.

**Comment by SidOfc** [comment]
No worries, always gets tricky with config and we're all human! As a general guideline I always try to isolate the conflicting plugins :)

Glad the issue is resolved and yeah, let me know if you find any other issues :+1:
