### ISSUE TITLE
URL not visible

### ISSUE THREAD

**Issue by AckslD** [SidOfc/mkdx#138]
**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [x] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

v0.5.0-dev+1048-g69103ff0c

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:
    `[text](link)`

**Expected**:

I should see `[text](link)`

**Actual**:

I see `[text]      `
I.e the url itself is hidden/invisible.

![output](https://user-images.githubusercontent.com/23341710/109789182-5c9c4c00-7c10-11eb-9ac0-55fec33d9798.gif)

**Comment by SidOfc** [comment]
Hmmn that's interesting indeed, when I try this, the link remains visible while my cursor is on the same line but I see that is not the case here. It looks like you have more plugins installed though, can you try this with only mkdx enabled and all other plugins disabled?

If the issue still occurs, could you provide a minimal vimrc file which I can try out on my machine?

**Comment by AckslD** [comment]
Sorry, I just found that the issue was caused by [indentLine](https://github.com/Yggdroot/indentLine). Putting the following two lines solved it for me and allows me to use both plugins:
```
let g:indentLine_concealcursor=""
let g:indentLine_conceallevel=2
```

**Comment by SidOfc** [comment]
No problem! thank you for checking and figuring out that the issue was related to the combination of mkdx + IndentLine :tada:
