### ISSUE TITLE
duplicate hyphens for lists with plasticboy/vim-markdown

### ISSUE THREAD

**Issue by bon-ami** [SidOfc/mkdx#150]
**OS type**:

- [ ] Unix
- [x] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [x] neovim
- [ ] Other ([SPECIFY])

**Vim version**:
NVIM v0.5.0-746-gf7cc3ae0b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
**Reproduce steps**:
Plug 'plasticboy/vim-markdown'
Plug 'SidOfc/mkdx'

1. Open a markdown file
2. write a line of list with "-"
3. [Enter]

**Expected**:
```
- former line
- 
```
**Actual**:
```
- former line
- -
```
Either vim-markdown or mkdx needs to fix for this. Since plasticboy does not seem so active, I wish I can get help from here. I have configured but no use. Thanks a lot.
```
let g:vim_markdown_new_list_item_indent = 0
```

**Comment by SidOfc** [comment]
Hello @bon-ami,

Unfortunately both mkdx and plasticboy/vim-markdown override enter, this means you'll have to choose to either use mkdx's enter handler or plasticboy's. mkdx enter handler can be disabled by setting `g:mkdx#settings.enter.enable` to `0`, for plasticboy I believe it's this section: https://github.com/plasticboy/vim-markdown#do-not-automatically-insert-bulletpoints

This is a plugin conflict and unfortunately can't be "fixed", only avoided.
I understand it's not the outcome any of us wish for, but it can't be helped, cheers for the feedback though :+1:

**Comment by bon-ami** [comment]
You are the best. The following line commented in vim-markdown
`setlocal comments+=b:*,b:+,b:-`
