### ISSUE TITLE
Compess anim-GIFs in the docs

### ISSUE THREAD

**Issue by totpet** [SidOfc/mkdx#16]
Hi!

I think the animated GIFs in the documentation inside the repository are needlessly large (I keep Vim plugins as git submodules), can you please compress them? You could use something like this:
`gifsicle -O2 --colors 256 --batch doc/gifs/*.gif`

This reduced their size from around 24 MB to 3.9 MB without a massive loss of quality, but other parameters or tools might give you better results.

Thanks!

**Comment by SidOfc** [comment]
Hi there.

Fair point, I will look into it, I will push the compressed gifs when I'm done, it will probably do some good for the README page load time as well :)

Cheers!

**Comment by SidOfc** [comment]
Hi again!

Latest [master](https://github.com/SidOfc/mkdx/commit/257d8f58d0c128e3fee617097e63286e371ce6f0) now contains reduced size for all gifs, 3.9MB with the above command.

Thanks you for your feedback!
