### ISSUE TITLE
enter function appears weird when the completion menu showing up

### ISSUE THREAD

**Issue by lee-shun** [SidOfc/mkdx#161]
Thank you for your excellent plugin!

**OS type**:

- [x] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [x] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**:
1. i have the following in my vimrc to use  deoplete.nvim
```vim
inoremap <expr> <cr> ((pumvisible())?("\<C-y>"):("\<cr>"))
inoremap <expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<TAB>"
```
2. and for mkdx:
```vim
" ===
" === mkdx
" ===
let g:mkdx#settings = {
            \'highlight': { 'enable': 0 },
            \'map': { 'prefix': '=' }
            \}
```

**Reproduce steps**:

1. when I try to input with complete menu powered by deoplete.nvim, enter will not change a new line:
![屏幕截图_1](https://user-images.githubusercontent.com/46647235/155866963-966735d4-08bd-4e8c-8795-00fc0a37de4f.png) to 
![屏幕截图_2](https://user-images.githubusercontent.com/46647235/155866970-5bc65157-d5f6-4996-8752-acce6664ba89.png)

4. if there is no complete menu, (for example, a space after), it works well:
![屏幕截图_3](https://user-images.githubusercontent.com/46647235/155866993-5e441845-bcc1-471a-a7ba-36fb8194a059.png)
to
![屏幕截图_4](https://user-images.githubusercontent.com/46647235/155866998-193d19a5-65ee-493e-9693-6318ad5d322b.png)

What happened????

**Comment by lee-shun** [comment]
got one possible solution:

It seems the popup menu take in the "cr" to confirm rather than actually insert a "\n"

So I put the following code in "after/ftplugin/markdown.vim"

```vim
" === patch mkdx
function! s:cr_close_pop()
  return pumvisible() ? "\<C-y>" : ""
endfunction
inoremap <silent> <Plug>(mkdx-enter-modify) <C-R>=<SID>cr_close_pop()<CR><C-R>=mkdx#EnterHandler()<Cr>:setlocal autoindent<Cr>
imap <buffer><silent> <CR> <Plug>(mkdx-enter-modify)
```

Then it works well...

**Comment by SidOfc** [comment]
Hello @lee-shun!

Would you mind forking mkdx and submitting a PR with the change you made? I'll have a look at it today and if all is well I'll merge it. Cheers for your efforts 👍

**Comment by lee-shun** [comment]
Thank you and this excellent plug! Cheers!

**Comment by SidOfc** [comment]
@lee-shun you should now be able to enable the behaviour by setting `:let g:mkdx#settings.enter.close_pum = 1` (in vimrc this must be written like `let g:mkdx#settings = {'enter': {'close_pum': 1}}`).

Leaving this open for you to confirm whether it works 👍

**Comment by lee-shun** [comment]
Just tested this neeeeew feature, Perfect!

**Comment by SidOfc** [comment]
Haha thanks!

Also cheers for reporting and doing the actual work, implementation was easy thanks to your efforts and may prove useful to people using other completion plugins as well 👍 

Enjoy :)
