### ISSUE TITLE
Jump to header not working with wiki links

### ISSUE THREAD

**Issue by lyndhurst** [SidOfc/mkdx#162]
**OS type**:
Unix
**Vim version**:
For vim: 8.2

Hi, 

The `mkdx-jump-to-header` function works fine when the fragment link is located within a regular markdown link, but it is not working for me when inside a 'wiki-link'.

I would not open an issue since your plugin is designed for markdown, but after reading #154 , I thought that if mappings are going to support ' wiki-links ', we might as well be able to use them for 'fragment-links'. Which is a very useful feature to shorten so called anchor links.

I personally use pandoc with the reference link option to format my markdown files, and  when playing around with fragment links, I also noticed that `mkdx-jump-to-header` does not work with the 'bare link format' used with reference links (e.g. `[Reference]: #fragment-link`) . This was to be expected, and is not a concern for me, but I thought I might as well let you know :)

Thank you in advance for your time.

**Comment by SidOfc** [comment]
Hello @lyndhurst, cheers for opening an issue!

What `mkdx-jump-to-header` does is gather a list of document headers (lines starting with one or more `#` or setex-style `---` and `===` headers) and collects them in a quickfix list (or fzf integration if you used the snippet) for you to select where to jump.

Are you sure this is an issue with `mkdx-jump-to-header` and not for example fragment link autocompletion?

**Comment by lyndhurst** [comment]
Hi, Thanks a lot for replying so quickly.

I might be lost a little, sorry about that. In my mind what you are describing above is `mkdx-quickfix-toc`, and the mapping I was trying to use on 'wiki links' is `<Plug>mkdx-jump-to-header` which I would describe as a 'follow link' type of action which optionally adds the current position to the jump list.

What I am trying to achieve is to follow a 'fragment link' to another section in the document.

When my cursor is positioned on a 'regular' markdown link like `[See section](#section)`, it works exactly as expected.

When my cursor is placed on a link that follows a 'wiki-link' format like `[[See section|#section]]`, nothing happens.

In both cases, I get the fragment link from fragment completion successfully, and I use the following mapping: 
 `nmap <buffer> <localleader>j <Plug>(mkdx-jump-to-header)`.

Note that I use `<buffer>` because the mapping is part of a 'filetype autocmd'; I do not think it is relevant anyway since the operation is successful in the first case scenario, so the mapping should be alright.

**Comment by SidOfc** [comment]
Ah thank you so much for clarifying @lyndhurst, the provided `[[See section|#section]]` example  is very clear 👍 I think I may have also confused myself here, you are indeed correct about the functionalities of `mkdx-quickfix-toc` vs `mkdx-jump-to-header`. I think this should be fairly easy to support as well.

Will get to it as soon as I have some free time on my hands, thanks again for the feedback!

**Comment by lyndhurst** [comment]
Nice, I am glad you feel it will be possible to support, it is a nice addition.

On my part, if you still need an update to the 'readme' with 'wiki link' examples as mentioned in #154 , I could try to give it a go. I say the 'readme' because this is how it is addressed in the issue, but I do not really see what could be added there, it might be the vim help page that you guys were talking about. In which case, I am not familiar with the syntax, so it might take me a little longer...

You let me know, and thanks again for taking the time.

**Comment by SidOfc** [comment]
Hi @lyndhurst, support should be implemented now, updating mkdx should make it work.

That said, it matches `[[#anchor|description]]` as I gathered from [MediaWiki](https://www.mediawiki.org/wiki/Help:Links#Internal_links) that this is the correct order.

It is still pretty easy to change this or to add some setting to control where the anchor should go however I wonder if this is needed. I might have been a bit hasty about closing this in the commit message since it might not be exactly what you want. I'll reopen until I see confirmation :)

As for the documentation update I guess we could add a small note to the "Jump to header" example section about wikilinks fragment links being supported.

**Comment by lyndhurst** [comment]
Wow, that was quick! Yes, I can confirm that it is working now, and you were right about the format, the URL comes first. Thank you again for your time.

**Comment by SidOfc** [comment]
No problem, thank you for the feedback as well :)

Enjoy 👍
