### ISSUE TITLE
Jump to header functionality stopped working with inline fragment links

### ISSUE THREAD

**Issue by lyndhurst** [SidOfc/mkdx#165]
Hi,

I found out a few days ago that `mkdx-jump-to-header` stopped working on my computer with markdown inline links. 

It is still working with 'wiki links' so I am wondering if it is related to #162 .

It would be helpful to know if you can reproduce it, Thanks in advance.

**Comment by SidOfc** [comment]
Hi @lyndhurst, indeed I can reproduce, might have been testing the "live" version of mkdx while I was working on #162 🤦 

Will check it out, cheers 👍

**Comment by SidOfc** [comment]
All of the following should now work:

```markdown
# hello world

Can I still jump to [markdown-link](#hello-world).
And to [[#hello-world|wiki-link]]
<a href="#hello-world">href-link</a>
<a id="hello-world">id-link</a>
```

Leaving this open for you to confirm as usual, thanks again for the report in the meantime 👍

**Comment by lyndhurst** [comment]
Yes, working again :+1: 
Thank you for fixing it so quickly.

**Comment by SidOfc** [comment]
No problem, happy Vimming!
