### ISSUE TITLE
Using + for lists

### ISSUE THREAD

**Issue by piotryordanov** [SidOfc/mkdx#167]
Hey, first off, thanks a lot for this awesome plugin! 

I was wondering if it is possible to create unordered lists with the `+` sign instead of the `-` sign.

I looked around the docs, and couldn't find a way to add symbols.

Thx in advance!

**Comment by SidOfc** [comment]
The documentation is rather large, it seems like the setting you want is: [g:mkdx#settings.tokens.enter](https://github.com/SidOfc/mkdx#gmkdxsettingstokensenter) :)

By default, mkdx understands `['-', '*', '>']` as things which require "special" handling when pressing enter. You can add `+` to this list and it'll work.

I've tested this locally so I'm fairly certain I can close this issue, if this does not work for you then feel free to add additional feedback of course!

**Comment by piotryordanov** [comment]
God dammit I knew it was somewhere and I missed it 🤣
I had found the one for checkboxes but didn't see this one!

Thx for the help 🙏
