### ISSUE TITLE
"o

### ISSUE THREAD

**Issue by wiwo192** [SidOfc/mkdx#171]
Hello there, thanks for reporting an issue or requesting a feature!
If you want to add a feature, you won't need this template. Just provide a clear
description of what you want and include an example of how this works in practice.

If you're opening a bug report,this template will help you fill out all the needed information,
simply replace the [TEMPLATE] data with actual information, fill out the checkboxes and include any
information you find useful and you're good to go!
When you're done, don't forget to re-read and remove dummy texts like this paragraph.

**OS type**:

- [ ] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

For vim: `vim -v`
For nvim: `nvim -v`

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:
   [EXAMPLE TEXT (for the maintainer to test with)]
3. Then, attempt to do [ACTION] in [MODE].

**Expected**:

Write the expected behaviour, e.g. what *should* have happened?

**Actual**:

Write what actually happened instead.

**Comment by SidOfc** [comment]
No problem, will close this one 👍
