### ISSUE TITLE
Agenda creation with Generate-TOC

### ISSUE THREAD

**Issue by natemart** [SidOfc/mkdx#177]
Great plugin! 
I use markdown for making agendas from categorized lists. I was thinking that using the same behavior as Generate-TOC to generate an agenda based on the list token would be great. So something like using a different token would designate an item for the agenda:

`- category1`
`- [ ] subject1`
 `      - [ ] item1`
 `   - [ ] subject 2`
`      * [ ]  item 1`
 `- category2`
`   - [ ] subject1`
 `      - [ ] item1`
 `      * [ ] item2`
 `      - [ ] item3`

`# Agenda`
`- [Agenda](#Agenda)`
`- [category1](category1)`
`   - [ ] subject2`
`      - [ ] item1`
`- [category2](category2)`
`   - [ ] subject1`
`      -  [ ] item2`

Or even if there was a way to designate what type of items were designated for the table of contents could be useful to.

**Comment by SidOfc** [comment]
Hi @natemart, cheers for the compliment :)

Unfortunately though, mkdx is on [feature freeze](https://github.com/SidOfc/mkdx/blob/master/CONTRIBUTING.md#requesting-a-feature). I've kind of moved on from regular Vim + VimL to Neovim + its Lua API and am basically no longer willing to invest time into building new features using VimL (or Vim9 for that matter).

mkdx is pretty much in maintenance mode, the code I wrote years ago also isn't something I can be too proud of looking back at today so I also wouldn't recommend diving in yourself as it might even redefine what "pain" means for you 😅 

Thanks for the time and thought put into the request, but I'm afraid I'm going to pass, sorry!
