### ISSUE TITLE
source .vimrc throws exception

### ISSUE THREAD

**Issue by jackywu** [SidOfc/mkdx#181]
**OS type**:

- macOS

**Vim**:

- MacVIM

**Vim version**:
![Xnip2023-02-24_20-55-58](https://user-images.githubusercontent.com/587955/221184175-9de20960-d82a-4f2f-9ba6-3f2e7f2f5003.png)

this is my `~/.vimrc` which relative to mkdx plugin:

```
        Plug 'SidOfc/mkdx'
        " let g:mkdx#settings = { 'map': { 'prefix': '\' }, 'highlight': { 'enable': 1 } }
        let g:mkdx#settings     = {
                                \ 'map': { 'prefix': '\' },
                                \ 'highlight': { 'enable': 1 },
                                \ 'enter': { 'shift': 1 },
                                \ 'links': { 'external': { 'enable': 1 } },
                                \ 'toc': { 'text': 'Table of Contents', 'update_on_write': 1 },
                                \ 'fold': { 'enable': 1 },
                                \ }
        autocmd FileType markdown set nonumber wrap | set foldmethod=manual | GitGutterDisable

```

**Reproduce steps**:

1. open a markdown file, and  `:vsp .vimrc`, change anything , and save
2. jump back to the markdown file
3. press 'o' to go into `insert mode`, vim throws excepiton

![Xnip2023-02-24_20-59-28](https://user-images.githubusercontent.com/587955/221184785-7e098a05-db59-456b-a2a6-c0def8b967ed.png)

**Comment by SidOfc** [comment]
Hello, I just checked some issues and #151 does provide a solution. Since it was rather ugly I decided to make some additional changes so that after updating you should be able to configure mkdx like so in your `.vimrc`:

```viml
call mkdx#configure({
      \ 'map': { 'prefix': '\' },
      \ 'highlight': { 'enable': 1 },
      \ 'enter': { 'shift': 1 },
      \ 'links': { 'external': { 'enable': 1 } },
      \ 'toc': { 'text': 'Table of Contents', 'update_on_write': 1 },
      \ 'fold': { 'enable': 1 },
      \ })
```

I tested this myself and it resolved the issue (this also happened on regular vim in the terminal). Please let me know if it does not work as intended.
