### ISSUE TITLE
activating mkdx syntax highlighting for .wiki filetype

### ISSUE THREAD

**Issue by alexandreroberts** [SidOfc/mkdx#182]
I would like to try out using mkdx syntax highlighting on .wiki files (organized by Lervag's Wiki.vim). Is there a simple way to tell mkdx to turn on not only for .md but also for .wiki files?

**Comment by SidOfc** [comment]
Not as far as I know, mkdx is purely a markdown filetype plugin and additionally is also on feature freeze / maintenance mode.

I'm not a syntax highlighting expert either by the way, the syntax file for mkdx is compiled from snippets of code from other plugins and mkdx specific highlights which I wrote myself (such as checkbox and list item highlighting).

I'd say a better solution would be to open an issue on Wiki.vim to ask if they could implement the highlight groups you're looking for in that plugin. I definitely do not mind snippets being copied from my plugin nor do I seek any explicit credit.

With all that said I'm going to close this issue. Thank you for the feedback and I hope Wiki.vim maintainers are interested and willing to implement this feature :)

**Comment by alexandreroberts** [comment]
That makes sense. Many thanks for the quick reply!
