### ISSUE TITLE
`<prefix>ln` does not always work when cursor is in the first column

### ISSUE THREAD

**Issue by camoz** [SidOfc/mkdx#187]
Linux, neovim v0.9.0

**Reproduce steps**:

1. Open a markdown file.
2. Paste the following example into the file:
    foo
    bar
3. Place cursor on `b`.
4. Do `<prefix>ln` in normal mode.

**Expected**:

`bar` gets turned into a link.

**Actual**:

`foo` gets turned into a link.

**Comment by SidOfc** [comment]
Cheers for the report and clear reproduction. I applied a patch which resolves this issue. Please feel free to comment if the issue persists after updating mkdx 👍

**Comment by camoz** [comment]
Thank you :)
