### ISSUE TITLE
time stamp gets recognized as ordered list

### ISSUE THREAD

**Issue by hellocode808** [SidOfc/mkdx#189]
To reproduce:
```
45:02 timestamp
02:02 timestamp 2
```
when you now put the cursor on `|45:02 timestamp` and press enter in insert mode, the result is
```
1.:02 timestamp
2.:02 timestamp 2
```

expected behaviour: it shouldn't change the time codes.

Also noticed that undo command is not available from here.

**Comment by SidOfc** [comment]
Hello there, I just merged a commit which fixes this. Let me know if the issue still persists.

Cheers for the report.

**Comment by hellocode808** [comment]
Great, thank you. Works perfectly now.
