### ISSUE TITLE
Numbered list issues

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#196]
Hello again! 

I know that you are no longer maintaining this plugin, but maybe you can help me with this annoying issue. 

So if I start a numbered list when I arrive at item 10 after that when I pres enter i no longer get item 11. If I go up, let's say on position 7 and press enter the list is reordered I and the last item is 11 as expected, but if I go to last item and press enter again I do not get 12. 

And another annoying thing is that if I have a list with more than 10 items and I edit it the items on lines greater than 9 get automatically indented.

Something like this

```
1. a
2. k
3. mk
4. bk
5. ak
6. ak
7. lkk
8. fjhjk
9. lkj
   10. lfksdjfks
   11. lkj
   12. lkfjlsjdfls
```

I disabled all other plugins in doing my tests and the same thing happens.

Thank you for your help and understanding!

**Comment by SidOfc** [comment]
Hello there,

I'm not entirely sure what is causing the indenting issue. When I run Neovim with the following `init.lua`:

```lua
-- CHANGE this to the installation directory of mkdx on your machine!
local mkdx_path = "/path/to/mkdx"

vim.opt.runtimepath:append({ mkdx_path })
vim.opt.runtimepath:append({ mkdx_path .. "/after" })
vim.opt.runtimepath:remove({ vim.env.HOME .. "/.config/nvim" })
vim.opt.packpath:remove({ vim.env.HOME .. "/.local/share/nvim/site" })

vim.opt.expandtab = true
vim.g.mapleader = " "
vim.g["mkdx#settings"] = {
	insert_indent_mappings = 1,
	enter = { shift = 1, o = 1, shifto = 1 },
}
```

Via command `nvim test.md -u test.init.lua` I'm not getting this indenting behavior when for example adding some text to list item nr 11 in my test file. Does the output of `:script` indeed confirm that no other plugins are being loaded?

I did just push a patch which should fix item handling for numbered list items going past 9.

Sorry for the (relatively) late reply, I was in France last week and actually didn't touch any computer there :)

Also, mkdx isn't entirely "dead" yet, it's in feature freeze / maintenance mode which just means no new features are added, and bugs which would require massive rewrites would likely also no longer be fixed since it wouldn't be worth the time investment.

In general though, if I think a bug can be fixed, or if someone else puts in the effort to do so (which I definitely wouldn't recommend for those wanting to stay sane) then I'll give it a shot for sure.

**Comment by samarulmeu** [comment]
Hello! So I  will answer bellow. 

> Hello there,
> 
> I'm not entirely sure what is causing the indenting issue. When I run Neovim with the following `init.lua`:
> 
> ```lua
> -- CHANGE this to the installation directory of mkdx on your machine!
> local mkdx_path = "/path/to/mkdx"
> 
> vim.opt.runtimepath:append({ mkdx_path })
> vim.opt.runtimepath:append({ mkdx_path .. "/after" })
> -- below paths are unix paths and will probably be different on windows
> vim.opt.runtimepath:remove({ vim.env.HOME .. "/.config/nvim" })
> vim.opt.packpath:remove({ vim.env.HOME .. "/.local/share/nvim/site" })
> 
> vim.opt.expandtab = true
> vim.g.mapleader = " "
> vim.g["mkdx#settings"] = {
> 	insert_indent_mappings = 1,
> 	enter = { shift = 1, o = 1, shifto = 1 },
> }
> ```
> 
> Via command `nvim test.md -u test.init.lua` I'm not getting this indenting behavior when for example adding some text to list item nr 11 in my test file. Does the output of `:script` indeed confirm that no other plugins are being loaded?

Indeed there is only the `mkdx` plugin loaded. Please try to create a list of 13 items let say and then try to add a new item after nr. 4, 5, 6 or 7 (for me it seems that this behavior appears somewhere in this range, less than 9 anyhow).

> I did just push a patch which should fix item handling for numbered list items going past 9.

The patch is working. Thank you so much!

> Sorry for the (relatively) late reply, I was in France last week and actually didn't touch any computer there :)

It's better to have some off the grid times. 

> Also, mkdx isn't entirely "dead" yet, it's in feature freeze / maintenance mode which just means no new features are added, and bugs which would require massive rewrites would likely also no longer be fixed since it wouldn't be worth the time investment.
> 
> In general though, if I think a bug can be fixed, or if someone else puts in the effort to do so (which I definitely wouldn't recommend for those wanting to stay sane) then I'll give it a shot for sure.

Thank you so much! I was not sure that what I have is a bug or something wrong with my configuration, although as I mentioned I eliminated all other plugins.

**Comment by SidOfc** [comment]
After checking this out again with your new instructions I was able to reproduce the issue.
I believe the latest commit fixes this behavior, it was broken in the same way as the other issue you mentioned. I updated the numbered list item pattern to fix that but didn't update it in one place which is where this went wrong.

Can you confirm the fix works as expected?

**Comment by samarulmeu** [comment]
Thank you so much! Now it is working the way it was supposed to! 

Great job!
