### ISSUE TITLE
Auto Indent of List Items not working

### ISSUE THREAD

**Issue by blackkenny** [SidOfc/mkdx#38]
**OS type**:
- [ ] Unix
- [ ] Windows
- [x] Mac OS 10.13.4

**Vim**:
- [x] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**: 
8.0.1283

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Create the same list as shown in the docs (Inserting List Items)
    https://github.com/SidOfc/mkdx#inserting-list-items
3. Type "Return" at the end of a line of a nested List Item

**Expected**:

A new List Item should be created at the same indentation level as the previous item. 
For numbered list items the list should look like this:

-> 1. 
-> 2.
---->  2.1
---->  2.2
-> 3. 

**Actual**:

The numbered list looks like this:

-> 1. 
-> 2.
----> 3. 
-> 4.
-> 5.

It looks like the plugin does not recognise the indent. 
I do not use any other vim plugins.

My .vimrc:
```
execute pathogen#infect()
syntax on
filetype plugin indent on

let mapleader = ','
```

**Comment by SidOfc** [comment]
Hi @blackkenny, thanks for reporting the issue, I'll look into it when I get home!

**Comment by blackkenny** [comment]
@SidOfc Thank you for the quick fix 👍
