### ISSUE TITLE
WrapText missing endif

### ISSUE THREAD

**Issue by paxtemper** [SidOfc/mkdx#4]
When i tray to wrap word (bold, italic..), wrapping is done successful but vim report error.

```
Error detected while processing function mkdx#WrapText:
line   14:
E171: Missing :endif
```

**Comment by SidOfc** [comment]
Hi there!

Thanks for reporting the issue, I'm going to take a look.

**Comment by SidOfc** [comment]
Hi pax,

I've added a test branch that you can checkout to see if it fixes your issue.
I could not reproduce it myself using either neovim or regular vim, hence I'd like to ask you to check this fix for me, let me know if you run into issues with the code below. (note that /path/to/mkdx must be replaced with the actual path in which your plugin manager installed the plugin in the `cd` command.).

To use this branch:

    $ cd ~/.vim/path/to/mkdx
    $ git pull origin wraptext-missing-endif
    $ git checkout wraptext-missing-endif

Then, open your markdown file and see if the error is still printed.
If the issue remains, could you please add the output of `which vim` and `vim -v` or, if you're using neovim `which nvim` and `nvim -v`.

**Comment by paxtemper** [comment]
Thanks for easy guide what i need to do.
When I'm on wraptext-missing-endif branch error is fixed.

**Comment by SidOfc** [comment]
Hi again pax!

I've merged the change into `master`, you can revert your branch back if you didn't do this already and update the plugin like normal!

Cheers!
