### ISSUE TITLE
Inserting list items is not working with unicode characters

### ISSUE THREAD

**Issue by yous** [SidOfc/mkdx#80]
**OS type**:

- [ ] Unix
- [ ] Windows
- [x] Other (macOS)

**Vim**:

- [x] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

8.1.500

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:
   ``` markdown
   - 😀 list item
   ```
3. Type <kbd>Enter</kbd> at the end of the line in INSERT mode.

**Expected**:

``` markdown
- 😀 list item
- |
```
The cursor is at `|`.

**Actual**:

``` markdown
- 😀 list item
|
```
The cursor is at `|`.

**Comment by SidOfc** [comment]
Hi there,

Thank you for the bug report, I will look into it!

**Comment by yous** [comment]
Now it works well, thank you for the quick update!
