### ISSUE TITLE
Helptags error

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#92]
When using the Vundle plugin manager (I don't know if it the case for the other plugin managers) when installing or updating I get this error:

```
Error running :helptags /home/username/vim/bundle/mkdx/doc
```

Executing `:helptags ~/.vim/bundle/mkdx/doc/` I narrowed down the problem:

```
E154: Duplicate tag "mkdx-function-wrap-text" in file /home/username/.vim/bundle/mkdx/doc//mkdx.txt
E154: Duplicate tag "mkdx-plug-checkbox-next-v" in file /home/username/.vim/bundle/mkdx/doc//mkdx.txt
```

**OS type**:

- [x] Unix

**Vim**:

- [x] vim

**Vim version**:

VIM 8.1

**Comment by SidOfc** [comment]
Hi @samarulmeu!

I've fixed the duplication in the helptags and pushed to master, you should no longer receive this warning.

Let me know if the issue persists, otherwise feel free to close 👍

**Comment by samarulmeu** [comment]
Perfect! And closing.
