### ISSUE TITLE
[Feature request] Block Code Wrapping

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#93]
Would it be possible to have a block code wrapping?

Currently only the inline code wrapping is supported using `` <PREFIX>` ``  in both Normal or Insert mode. Maybe you could provide the same mapping and have inline code for only parts of a line and block code when more than one line are selected? 

Thank you!

**Comment by SidOfc** [comment]
Hey @samarulmeu, 

This could indeed be a nice feature for mkdx, may I ask how you would actually "apply" this feature? So for example, do you intend to visually select that which needs to be wrapped before performing a mapping?

Let me know! :+1:

**Comment by samarulmeu** [comment]
Exactly. I will select some lines of code and then press the appropiate mapping and they should be enclosed inside a block code.

I think that it should be the same as you've already done in the case of inline code block (which works but only if you select maximum a line).

**Comment by SidOfc** [comment]
I'm not quite there yet, but was having quite some fun already with this snippet:

```viml
fun! mkdx#WrapSelectionInCode() range
  let is_linewise = getpos("'>")[2] > 10000000

  if is_linewise
    return "xi```\<Cr>```\<Cr>\<Esc>2kp"
  else
    return ":\<C-U>call mkdx#WrapText('v', '`', '`')\<Cr>"
  end
endfun
```

The downside to this solution is that when your selection has leading or trailing newlines, they will also be wrapped, most of the time this is undesired so will look into that next :)

**Comment by samarulmeu** [comment]
I think you are trying to hard. I don't think that the new feature has to take into account the leading or trailing newlines --- the selection is the user's concern: he **selects** what he wants to enclose in a code block and if, by mistake or not, he also selects leading/trailing newlines and does not want them inside the block **he** should correct the mistake.

So, new feature only concern should be to add ` ``` `  before and after the selection.

**Comment by samarulmeu** [comment]
How do you access what you have implemented `mkdx#WrapSelectionInCode()`? I tried using the mapping for the inline code, but I still get the old behavior.

**Comment by SidOfc** [comment]
@samarulmeu hey! this is just a test snippet, it's not in master at the moment, just showing an example -- so far -- hehe

About trying to hard, actually, it is my own expectation that this should work. When I want to enclose some code, I do not want to "nitpick" the lines exactly, I _expect_ the plugin to be smart enough in that case to handle leading and trailing lines. The plugin intends to be "easy to use" not to teach you proper conventions ;)

It is also exactly this difference in mentality why having discussions about it here is important too :)
If you think I am wrong here, feel free to suggest otherwise, always wondering what mkdx users think about these kinds of things!

**Comment by samarulmeu** [comment]
> @samarulmeu hey! this is just a test snippet, it's not in master at the moment, just showing an example -- so far -- hehe

Aha! Thank you!

> About trying to hard, actually, it is my own expectation that this should work. When I want to enclose some code, I do not want to "nitpick" the lines exactly, I _expect_ the plugin to be smart enough in that case to handle leading and trailing lines. The plugin intends to be "easy to use" not to teach you proper conventions ;)

The way you envision the plugin's behavior is nice, but, if it is hard to implement (not to mention that sometimes it is impossible), I think you should also take into account the fact that the user **should** know what he is doing/wanting.

> It is also exactly this difference in mentality why having discussions about it here is important too :)
> If you think I am wrong here, feel free to suggest otherwise, always wondering what mkdx users think about these kinds of things!

I really appreciate your support and the fact that you try to solve every issue and listen to the users.

**Comment by SidOfc** [comment]
Issues are there to be solved!

And it can help to have discussions to link to, where things have been iterated before too so I always am open :)

I do not think the implementation is "hard" to build, but the way the text gets inserted is a bit different which is just something I need to learn to master.

If I never master it, I can never build such features, so I take the challenge to "improve" my skillset / way of thinking as well even though this is "just a markdown plugin" :)

If it takes too long however, I'll add the "primitive" feature so it can be used sooner, and work more on it behind the scenes, releasing the "refinement" when it's ready, perhaps that is a better idea :thinking:

**Comment by samarulmeu** [comment]
It is not about taking too long, it is about when you feel confortable with your work. Please do not consider that I am eager to see it implemented and cannot wait.

I know you are using your time to deliver an amazing plugin for free and I truely appreciate your effort. 

So do the things in your own pace.

**Comment by SidOfc** [comment]
@samarulmeu should be in master,
going into `v`isual mode triggers inline codeblock even if selection is multiline.
to do block quotes go into linewise `V`isual, make a selection and press the usual keymapping.

Lemme know if there are any issues :crossed_fingers:

**Comment by samarulmeu** [comment]
Thank you so much! It works perfectly! Amazing job as always.

And closing...
